export interface DocItem {
  title: string
  description: string
  href: string
  section: string
  keywords?: string[]
}

export const docsSearchDataIT: DocItem[] = [
  // Getting Started
  {
    title: "Come iniziare",
    description: "Guida introduttiva a Verbalist",
    href: "/guide/getting-started",
    section: "Introduzione",
    keywords: ["inizio", "primo", "tutorial", "guida"],
  },
  // Analisi SERP
  {
    title: "Analisi SERP",
    description: "Panoramica dell'analisi SERP",
    href: "/guide/analisi-serp",
    section: "Analisi SERP",
    keywords: ["serp", "google", "ricerca"],
  },
  {
    title: "Come funziona l'analisi",
    description: "Scopri come Verbalist analizza i risultati di ricerca",
    href: "/guide/analisi-serp/come-funziona",
    section: "Analisi SERP",
    keywords: ["funzionamento", "processo"],
  },
  {
    title: "Analisi competitor",
    description: "Analizza i contenuti dei competitor",
    href: "/guide/analisi-serp/competitor",
    section: "Analisi SERP",
    keywords: ["concorrenti", "competitori"],
  },
  {
    title: "Filtri avanzati",
    description: "Utilizza i filtri per raffinare l'analisi",
    href: "/guide/analisi-serp/filtri",
    section: "Analisi SERP",
    keywords: ["filtrare", "avanzato"],
  },
  {
    title: "Interpretazione risultati",
    description: "Come interpretare i dati dell'analisi",
    href: "/guide/analisi-serp/interpretazione",
    section: "Analisi SERP",
    keywords: ["leggere", "capire", "dati"],
  },
  {
    title: "Export dati SERP",
    description: "Esporta i risultati dell'analisi",
    href: "/guide/analisi-serp/export",
    section: "Analisi SERP",
    keywords: ["esportare", "scaricare", "csv"],
  },
  // Pattern
  {
    title: "Analisi Pattern",
    description: "Panoramica dell'analisi dei pattern",
    href: "/guide/pattern",
    section: "Pattern",
    keywords: ["struttura", "modelli"],
  },
  {
    title: "Come funziona l'analisi pattern",
    description: "Scopri come vengono estratti i pattern",
    href: "/guide/pattern/come-funziona",
    section: "Pattern",
    keywords: ["funzionamento", "estrazione"],
  },
  {
    title: "Analisi heading",
    description: "Pattern delle intestazioni H1-H6",
    href: "/guide/pattern/heading",
    section: "Pattern",
    keywords: ["h1", "h2", "titoli", "intestazioni"],
  },
  {
    title: "Analisi topic",
    description: "Topic e argomenti trattati",
    href: "/guide/pattern/topic",
    section: "Pattern",
    keywords: ["argomenti", "temi"],
  },
  {
    title: "Word count",
    description: "Analisi della lunghezza dei contenuti",
    href: "/guide/pattern/word-count",
    section: "Pattern",
    keywords: ["parole", "lunghezza", "conteggio"],
  },
  {
    title: "Content gap",
    description: "Identifica lacune nei contenuti",
    href: "/guide/pattern/content-gap",
    section: "Pattern",
    keywords: ["lacune", "mancanze", "gap"],
  },
  {
    title: "Analisi E-E-A-T",
    description: "Segnali di Experience, Expertise, Authority, Trust",
    href: "/guide/pattern/eeat",
    section: "Pattern",
    keywords: ["esperienza", "autorevolezza", "fiducia"],
  },
  // Scraping
  {
    title: "Scraping competitor",
    description: "Panoramica dello scraping",
    href: "/guide/scraping",
    section: "Scraping",
    keywords: ["estrazione", "contenuti"],
  },
  {
    title: "Come funziona lo scraping",
    description: "Il processo di estrazione dei contenuti",
    href: "/guide/scraping/come-funziona",
    section: "Scraping",
    keywords: ["funzionamento", "processo"],
  },
  {
    title: "Conversione contenuti",
    description: "Converti HTML in Markdown",
    href: "/guide/scraping/conversione",
    section: "Scraping",
    keywords: ["markdown", "html", "convertire"],
  },
  {
    title: "Contenuti protetti",
    description: "Gestione di paywall e contenuti bloccati",
    href: "/guide/scraping/contenuti-protetti",
    section: "Scraping",
    keywords: ["paywall", "bloccati", "protetti"],
  },
  {
    title: "Export contenuti",
    description: "Esporta i contenuti estratti",
    href: "/guide/scraping/export",
    section: "Scraping",
    keywords: ["esportare", "scaricare"],
  },
  // Generazione
  {
    title: "Generazione contenuto",
    description: "Panoramica della generazione AI",
    href: "/guide/generazione",
    section: "Generazione",
    keywords: ["ai", "creare", "scrivere"],
  },
  {
    title: "Come funziona la generazione",
    description: "Il processo di generazione dei contenuti",
    href: "/guide/generazione/come-funziona",
    section: "Generazione",
    keywords: ["funzionamento", "processo", "ai"],
  },
  {
    title: "Modelli AI",
    description: "Scegli il modello AI più adatto",
    href: "/guide/generazione/modelli",
    section: "Generazione",
    keywords: ["gpt", "claude", "llm", "modello"],
  },
  {
    title: "Parametri generazione",
    description: "Configura i parametri di generazione",
    href: "/guide/generazione/parametri",
    section: "Generazione",
    keywords: ["configurare", "impostazioni"],
  },
  {
    title: "Tone of voice",
    description: "Personalizza il tono del contenuto",
    href: "/guide/generazione/tone",
    section: "Generazione",
    keywords: ["tono", "stile", "voce"],
  },
  {
    title: "Editing contenuto",
    description: "Modifica il contenuto generato",
    href: "/guide/generazione/editing",
    section: "Generazione",
    keywords: ["modificare", "editare"],
  },
  {
    title: "Rigenerare contenuto",
    description: "Rigenera sezioni specifiche",
    href: "/guide/generazione/rigenerare",
    section: "Generazione",
    keywords: ["rifare", "nuovo"],
  },
  {
    title: "Export contenuto",
    description: "Esporta il contenuto finale",
    href: "/guide/generazione/export",
    section: "Generazione",
    keywords: ["esportare", "scaricare", "word", "html"],
  },
  // Configurazione
  {
    title: "Configurazione",
    description: "Panoramica delle impostazioni",
    href: "/guide/configurazione",
    section: "Configurazione",
    keywords: ["impostazioni", "settings"],
  },
  {
    title: "Account",
    description: "Gestisci il tuo account",
    href: "/guide/configurazione/account",
    section: "Configurazione",
    keywords: ["profilo", "utente"],
  },
  {
    title: "Progetti",
    description: "Gestione dei progetti",
    href: "/guide/configurazione/progetti",
    section: "Configurazione",
    keywords: ["gestire", "organizzare"],
  },
  {
    title: "API",
    description: "Configurazione API e integrazioni",
    href: "/guide/configurazione/api",
    section: "Configurazione",
    keywords: ["chiave", "integrazione", "webhook"],
  },
  // Best Practices
  {
    title: "Best practice",
    description: "Consigli per ottenere i migliori risultati",
    href: "/guide/best-practice",
    section: "Best Practice",
    keywords: ["consigli", "suggerimenti", "ottimizzare"],
  },
]

export const docsSearchDataEN: DocItem[] = [
  // Getting Started
  {
    title: "Getting Started",
    description: "Introduction guide to Verbalist",
    href: "/en/docs/getting-started",
    section: "Introduction",
    keywords: ["start", "first", "tutorial", "guide"],
  },
  // SERP Analysis
  {
    title: "SERP Analysis",
    description: "Overview of SERP analysis",
    href: "/en/docs/serp-analysis",
    section: "SERP Analysis",
    keywords: ["serp", "google", "search"],
  },
  {
    title: "How it works",
    description: "Learn how Verbalist analyzes search results",
    href: "/en/docs/serp-analysis/how-it-works",
    section: "SERP Analysis",
    keywords: ["process", "workflow"],
  },
  {
    title: "Competitor analysis",
    description: "Analyze competitor content",
    href: "/en/docs/serp-analysis/competitors",
    section: "SERP Analysis",
    keywords: ["competition", "rivals"],
  },
  {
    title: "Advanced filters",
    description: "Use filters to refine analysis",
    href: "/en/docs/serp-analysis/filters",
    section: "SERP Analysis",
    keywords: ["filter", "advanced"],
  },
  {
    title: "Interpretation",
    description: "How to interpret analysis data",
    href: "/en/docs/serp-analysis/interpretation",
    section: "SERP Analysis",
    keywords: ["read", "understand", "data"],
  },
  {
    title: "Export SERP data",
    description: "Export analysis results",
    href: "/en/docs/serp-analysis/export",
    section: "SERP Analysis",
    keywords: ["export", "download", "csv"],
  },
  // Patterns
  {
    title: "Pattern Analysis",
    description: "Overview of pattern analysis",
    href: "/en/docs/patterns",
    section: "Patterns",
    keywords: ["structure", "models"],
  },
  {
    title: "How patterns work",
    description: "Learn how patterns are extracted",
    href: "/en/docs/patterns/how-it-works",
    section: "Patterns",
    keywords: ["process", "extraction"],
  },
  {
    title: "Heading analysis",
    description: "H1-H6 heading patterns",
    href: "/en/docs/patterns/headings",
    section: "Patterns",
    keywords: ["h1", "h2", "titles", "headers"],
  },
  {
    title: "Topic analysis",
    description: "Topics and themes covered",
    href: "/en/docs/patterns/topics",
    section: "Patterns",
    keywords: ["subjects", "themes"],
  },
  {
    title: "Word count",
    description: "Content length analysis",
    href: "/en/docs/patterns/word-count",
    section: "Patterns",
    keywords: ["words", "length", "count"],
  },
  {
    title: "Content gap",
    description: "Identify content gaps",
    href: "/en/docs/patterns/content-gap",
    section: "Patterns",
    keywords: ["gaps", "missing"],
  },
  {
    title: "E-E-A-T Analysis",
    description: "Experience, Expertise, Authority, Trust signals",
    href: "/en/docs/patterns/eeat",
    section: "Patterns",
    keywords: ["experience", "authority", "trust"],
  },
  // Scraping
  {
    title: "Competitor Scraping",
    description: "Overview of scraping",
    href: "/en/docs/scraping",
    section: "Scraping",
    keywords: ["extraction", "content"],
  },
  {
    title: "How scraping works",
    description: "The content extraction process",
    href: "/en/docs/scraping/how-it-works",
    section: "Scraping",
    keywords: ["process", "workflow"],
  },
  {
    title: "Content conversion",
    description: "Convert HTML to Markdown",
    href: "/en/docs/scraping/conversion",
    section: "Scraping",
    keywords: ["markdown", "html", "convert"],
  },
  {
    title: "Protected content",
    description: "Handling paywalls and blocked content",
    href: "/en/docs/scraping/protected-content",
    section: "Scraping",
    keywords: ["paywall", "blocked", "protected"],
  },
  {
    title: "Export content",
    description: "Export extracted content",
    href: "/en/docs/scraping/export",
    section: "Scraping",
    keywords: ["export", "download"],
  },
  // Generation
  {
    title: "Content Generation",
    description: "Overview of AI generation",
    href: "/en/docs/generation",
    section: "Generation",
    keywords: ["ai", "create", "write"],
  },
  {
    title: "How generation works",
    description: "The content generation process",
    href: "/en/docs/generation/how-it-works",
    section: "Generation",
    keywords: ["process", "workflow", "ai"],
  },
  {
    title: "AI Models",
    description: "Choose the right AI model",
    href: "/en/docs/generation/models",
    section: "Generation",
    keywords: ["gpt", "claude", "llm", "model"],
  },
  {
    title: "Generation parameters",
    description: "Configure generation parameters",
    href: "/en/docs/generation/parameters",
    section: "Generation",
    keywords: ["configure", "settings"],
  },
  {
    title: "Tone of voice",
    description: "Customize content tone",
    href: "/en/docs/generation/tone",
    section: "Generation",
    keywords: ["tone", "style", "voice"],
  },
  {
    title: "Content editing",
    description: "Edit generated content",
    href: "/en/docs/generation/editing",
    section: "Generation",
    keywords: ["modify", "edit"],
  },
  {
    title: "Regenerate content",
    description: "Regenerate specific sections",
    href: "/en/docs/generation/regenerate",
    section: "Generation",
    keywords: ["redo", "new"],
  },
  {
    title: "Export content",
    description: "Export final content",
    href: "/en/docs/generation/export",
    section: "Generation",
    keywords: ["export", "download", "word", "html"],
  },
  // Configuration
  {
    title: "Configuration",
    description: "Overview of settings",
    href: "/en/docs/configuration",
    section: "Configuration",
    keywords: ["settings", "options"],
  },
  {
    title: "Account",
    description: "Manage your account",
    href: "/en/docs/configuration/account",
    section: "Configuration",
    keywords: ["profile", "user"],
  },
  {
    title: "Projects",
    description: "Project management",
    href: "/en/docs/configuration/projects",
    section: "Configuration",
    keywords: ["manage", "organize"],
  },
  {
    title: "API",
    description: "API configuration and integrations",
    href: "/en/docs/configuration/api",
    section: "Configuration",
    keywords: ["key", "integration", "webhook"],
  },
  // Best Practices
  {
    title: "Best Practices",
    description: "Tips for best results",
    href: "/en/docs/best-practices",
    section: "Best Practices",
    keywords: ["tips", "advice", "optimize"],
  },
]
